export const MERCHANT_BANNER_IDS: {
  [key: number]: { name: string; priority: number }
} = {
  1: { name: 'Target', priority: 1 },
  2: { name: 'Costco Wholesale Corp.', priority: 1 },
  3: { name: 'CVS', priority: 2 },
  4: { name: 'Dollar General', priority: 1 },
  5: { name: 'Dollar Tree', priority: 2 },
  6: { name: 'Kroger', priority: 1 },
  7: { name: 'Publix Super Markets', priority: 1 },
  8: { name: 'Safeway', priority: 1 },
  9: { name: "Sam's Club", priority: 1 },
  10: { name: 'Walgreens', priority: 1 },
  11: { name: 'Walmart US', priority: 1 },
  12: { name: 'Staples', priority: 1 },
  15: { name: 'Home Depot', priority: 1 },
  16: { name: "Lowe's Home Improvement", priority: 1 },
  17: { name: 'Acme Markets', priority: 2 },
  19: { name: 'Meijer', priority: 2 },
  20: { name: 'Albertsons', priority: 2 },
  22: { name: 'ShopRite', priority: 2 },
  23: { name: 'Jewel-Osco', priority: 2 },
  31: { name: 'Food 4 Less', priority: 1 },
  33: { name: 'Harris Teeter', priority: 1 },
  40: { name: 'Ralphs', priority: 1 },
  44: { name: 'H-E-B', priority: 1 },
  45: { name: "BJ's Wholesale Club", priority: 2 },
  52: { name: 'Wegmans Food Market', priority: 2 },
  53: { name: 'Fred Meyer', priority: 1 },
  54: { name: 'Sprouts Farmers Market', priority: 2 },
  56: { name: 'Hy-Vee', priority: 3 },
  63: { name: 'Vons', priority: 2 },
  142: { name: 'Food Lion', priority: 2 },
  143: { name: 'Rite Aid', priority: 3 },
  144: { name: 'Giant Eagle', priority: 3 },
  165: { name: 'Family Dollar', priority: 2 },
  171: { name: 'Sephora', priority: 2 },
  177: { name: 'Best Buy', priority: 2 },
  5718: { name: 'Costco CA', priority: 1 },
  5849: { name: 'Walmart CA', priority: 1 },
  5917: { name: "Marshall's", priority: 3 },
  5921: { name: 'TJ Maxx', priority: 3 },
  5929: { name: "Kohl's", priority: 2 },
  6036: { name: 'ASDA', priority: 3 },
  6048: { name: 'Sainsburys UK', priority: 3 },
  6051: { name: 'Tesco', priority: 3 },
  6059: { name: 'Carrefour ES', priority: 3 },
  6074: { name: 'Bed Bath & Beyond', priority: 3 },
  6127: { name: 'Staples CA', priority: 2 },
  6162: { name: 'Dicks Sporting Goods', priority: 3 },
  6457: { name: 'Gap', priority: 3 },
  6677: { name: 'Starbucks', priority: 1 },
  6802: { name: "Macy's", priority: 2 },
  7610: { name: 'Coles', priority: 3 },
  8366: { name: "Domino's Pizza", priority: 2 },
  8598: { name: 'Taco Bell', priority: 2 },
  8643: { name: 'Amazon US', priority: 1 },
  8646: { name: 'Woolworths', priority: 3 },
  8652: { name: 'Instacart', priority: 1 },
  8662: { name: 'Ulta Beauty', priority: 3 },
  8712: { name: 'Nike Factory Store', priority: 3 },
  9016: { name: 'Shipt', priority: 2 },
  9137: { name: 'Uber Eats', priority: 1 },
  9947: { name: 'Chewy', priority: 2 },
  10068: { name: 'Seamless', priority: 3 },
  10078: { name: 'Amazon UK', priority: 1 },
  10208: { name: 'Grubhub', priority: 2 },
  10241: { name: 'Doordash', priority: 1 },
  10934: { name: 'Drizly', priority: 3 },
  12099: { name: 'Amazon CA', priority: 1 },
  12686: { name: 'Amazon ES', priority: 1 },
  12687: { name: 'Amazon DE', priority: 1 },
  12688: { name: 'Amazon FR', priority: 1 },
  12691: { name: 'Shein ES', priority: 2 },
  12749: { name: 'PC Express', priority: 3 },
  12819: { name: 'Temu', priority: 2 },
  12848: { name: 'Shein UK', priority: 2 },
  12849: { name: 'AliExpress', priority: 2 },
  12850: { name: 'Uber Eats UK', priority: 1 },
  12882: { name: 'Shein US', priority: 2 },
  12948: { name: 'Amazon AU', priority: 1 },
  19671: { name: 'Postmates', priority: 3 },
}
